version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "staging"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "pydantic"
        versions: [">=2"]
