# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.14"
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/rtts/djhtml
    rev: '3.0.6'  # replace with the latest tag on GitHub
    hooks:
      - id: djhtml
      - id: djcss
      - id: djjs
  - repo: local
    hooks:
      - id: pre-commit-django-migrations
        name: Check django migrations
        entry: python manage.py makemigrations --check --dry-run --no-input
        language: system
        types: [python]
        pass_filenames: false
