version: "3.8"

services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=puzzup_user
      - POSTGRES_PASSWORD=puzzup_password
      - POSTGRES_DB=puzzup
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/:Z
      - /usr/src/app/node_modules
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgres://puzzup_user:puzzup_password@db/puzzup
    env_file:
      - ./.env
    entrypoint:
      - ./docker-entrypoint.sh
    depends_on:
      - db
  discord:
    build: .
    command: python manage.py discord_daemon
    volumes:
      - .:/usr/src/app/:Z
    environment:
      - DATABASE_URL=postgres://puzzup_user:puzzup_password@db/puzzup
    env_file:
      - ./.env
    entrypoint:
      - ./docker-entrypoint.sh
    depends_on:
      - db
      - web

volumes:
  postgres_data:
